# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: >
    Ben's PC Parts
email: bgodfr5236@greenvilleschools.us
description: > # this means to ignore newlines until "baseurl:"
  This is a fake shopping site for a web design class.
  Nothing that is "ordered" through this site will ever 
  be charged to your card or will ever be delivered.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bgodfr5236.github.io/shopping-cart/" # the base hostname & protocol for your site
github_username:  bgodfr5236

# Build settings
markdown: kramdown
